### ISSUE TITLE
Cannot process image larger than 2 MB

### ISSUE THREAD

**Issue by blu94** [Intervention/image#781]
I'm not encounter the problem when uploading, this problem happen when i process the file on the server, i also update the php.ini file on the memory and max upload file size, but not helping, 

my php.ini setting:
```
memory_limit=256M
upload_max_filesize=32M
```

here is my code:

       ```
 // open an image file
        $img = Image::make('msg-1-fc-40.jpg');

        // finally we save the image as a new file
        $img->save('test.jpg');
        //
```
The image is larger then 2 MB, when i do this, it return me

This page isn’t working

shamirac.dev is currently unable to handle this request.
HTTP ERROR 500

can i know what happen?

**Comment by samthomson** [comment]
you might need to update the post max size too. If that doesn't work look in your php error logs.

**Comment by rafaelxavierborges** [comment]
@samthomson I'm with post_max_size = 128M but it returns ERROR 500 too. Same problem here @blu94 .

**Comment by samthomson** [comment]
Spit out your php.ini settings. IF you're running it on the server and not uploading like @blu94 then you may need to set the ini for php-cli and not php-fpm.

**Comment by kslimani** [comment]
@blu94 any feedback on this issue ? have you checked if you get a `PHP Fatal error : Allowed memory size of xxxx bytes exhausted` ?

**Comment by rafaelxavierborges** [comment]
I could sove this issue. It was solved modifying some configurations in php.ini file.

See bellow:
upload_max_filesize = 50M
memory_limit = 512M
max_input_time = -1
max_execution_time = 0

**Comment by challet** [comment]
512M for handling a 2M image ? I wouldn' call that solved :p

**Comment by blu94** [comment]
512 M memory limit doesn't solve the problem, i increase it to 1000, then only work fine, but, this sound crazy when the project is on share hosting

**Comment by aGervais** [comment]
I've also been struggling w/ OOM errors on my 128Mb nginx server (Docker'ized). From my debugging; I see the memory usage spike from 15Mb right up to 135Mb w/ one single image resize. The spike happens right after the line that calls the GD PHP library's imagecreatefromstring() method which is apparently notorious for memory usage.

`$resource = @imagecreatefromstring($binary);`

**Comment by kslimani** [comment]
It is not specified in the readme, but it is required to call [destroy()](http://image.intervention.io/api/destroy) method when you are done. _(for example when using Intervention\Image\Facades\Image)_

**Comment by Awilum** [comment]
It is resolved or not ?

**Comment by seniorYsir** [comment]
i have the same issue too.i just read the image from the document root.when the size is larger than 2 mb,the command 'Image::make($url)' is failure.

**Comment by Hervera** [comment]
Image operations tend to be quite memory exhausting because image handling libraries usually 'unpack' all the pixels to memory. 

A JPEG file of 3MB can thus easily grow to 60MB in memory and that's when you've probably hit the memory limit allocated for PHP.

As far I remember, XAMP only allocates 128 MB RAM for PHP.

Check your **php.ini** and increase the memory limit, e.g.:
`memory_limit = 512MB`

Then restart the server.

But this is not a good approach, the best approach is to compress and resize any image before saving it to the server.

**Comment by ltahuilan** [comment]
Thanks.
I had problems with files larger than 5MB, setting memory_limit=512 fixed it. I noticed that the RAM usage goes up about 200MB when uploading the file.

**Comment by gangwarrajeev** [comment]
> Thanks. I had problems with files larger than 5MB, setting memory_limit=512 fixed it. I noticed that the RAM usage goes up about 200MB when uploading the file.

Hi, I had same issue on server, but when increased my memory limit to ini_set('memory_limit','-1') it works fine.

**Comment by justijndepover** [comment]
I have the same issue, but I'm using a shared hosting and cannot increase the memory limit above 128M.
How can I solve this?

**Comment by samthomson** [comment]
@justijndepover at the risk of sounding patronising, have you asked your hosts if they can change it? Often these vars can be set by them per client (as it's all virtualised and rarely shared anyway). Some even have an admin panel where you can tweak it.
