### ISSUE TITLE
Not changing driver in Laravel 6

### ISSUE THREAD

**Issue by tyson-nw** [Intervention/image#971]
I cannot get Intervention/Image to change the driver in Laravel 6. Following the Laravel 5 instructions, I have added it to the providers and aliases in `config/app.php`. I run ` php artisan vendor:publish --provider="Intervention\Image\ImageServiceProviderLaravel5"`. Then I go into config/image.php and change the driver from gd to imagick. But I keep getting an error that it is trying to use the GD library. Am I missing a config step? Or is Intervention just not fully Laravel 6 compatible?

**Comment by DanielGilB** [comment]
Intervention is not compatible with Laravel 6. I updated to L6 and stops working.

**Comment by tyson-nw** [comment]
I think it might have something to do with the configure, I was able to bypass it and get it working, or at least the resizing parts working.

I was able to configure it on the fly in the module that called it and it seems to be working in Laravel 6.0.3 with intervention/image 2.5.0

1. `use Intervention\Image\ImageManagerStatic as Image;`
2. first in the method that uses it I included `Image::configure(array('driver' => 'imagick'));`
3. `Image::make($instance->thumbnail)->fit('400','400')->encode('png')`

It is hacky, and it will probably break if I do anything more complex, but it seems to be functional at the moment.

**Comment by olivervogel** [comment]
Issue should be fixed in 2.5.1 (abbf18d5ab8367f96b3205ca3c89fb2fa598c69e).

**Comment by tilecreature** [comment]
I just created a new laravel 6 project and this issue doesnt appear to be fixed, hence why im here, but the work around works great.

**Comment by Luppakorva** [comment]
@olivervogel can confirm it's not fixed yet. Changing config to imagick takes no effect in Laravel 6. fresh project.
